const studentSub = <p className="subtitle">at the University of California, <span style={{color: "#e36868"}}>Berkeley</span> studying both <span style={{color: "#e36868"}}>Computer Science</span> and <span style={{color: "#e36868"}}>Music</span>. Some other areas of interest include <span style={{color: "#e36868"}}>game design/development</span> and <span style={{color: "#e36868"}}>mathematics</span>, reflected in my participation in Berkeley's <span style={{color: "#e36868"}}>GDD</span> (Game Design and Development) and <span style={{color: "#e36868"}}>SAAS</span> (Student Association for Applied Statistics).</p>
const developerSub = <p className="subtitle">experienced in <span style={{color: "#e36868"}}>backend</span> work, such as creating <span style={{color: "#e36868"}}>Flask</span> apps, hosting said apps on platforms like <span style={{color: "#e36868"}}>Heroku</span>, and handling frontend queries with <span style={{color: "#e36868"}}>Python</span>. These skills are highlighted in my most recent team project: a community-based wildfire tracker called <span style={{color: "#e36868"}}>Fire Talk</span>.</p>
const gameCreatorSub = <p className="subtitle">whose inspiration is drawn from the <span style={{color: "#e36868"}}>MMORPG</span> genre as well as companies like <span style={{color: "#e36868"}}>Nintendo</span> and <span style={{color: "#e36868"}}>Square Enix</span>. Besides currently working on a project at GDD that will soon be released on <span style={{color: "#e36868"}}>Steam</span>, I like undertaking my own personal projects to be published on <span style={{color: "#e36868"}}>Itch</span>.</p>
const composerSub = <p className="subtitle">that aspires to <span style={{color: "#e36868"}}>heighten</span> the immersive experience from the <span style={{color: "#e36868"}}>games</span> that I make. In conjunction with making music as the <span style={{color: "#e36868"}}>Head of Music</span> in my project at GDD, I also enjoy <span style={{color: "#e36868"}}>arranging</span> others' music, allowing others to see it from a brand new perspective.</p>
const transcriberSub = <p className="subtitle">who enjoys <span style={{color: "#e36868"}}>learning</span> about the music I love by <span style={{color: "#e36868"}}>recreating</span> the music I love. By transcribing, I can train my <span style={{color: "#e36868"}}>ear</span> to pick apart melody, harmony, and percussion while also gaining <span style={{color: "#e36868"}}>insight</span> into how my favorite composers do what they do.</p>

export {
    studentSub,
    developerSub,
    gameCreatorSub,
    composerSub,
    transcriberSub,
}